# This is a basic workflow to help you get started with Actions

name: knit-rmd

# Controls when the workflow will run
on:
  # Schedules the workflow on cron
  schedule:
    - cron: '*/45 * * * *'

  # Allows you to run this workflow manually from the Actions tab.
  # Uncomment for testing, comment to run cron.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
      

      - name: Install cURL Headers
        run: sudo apt-get install libcurl4-openssl-dev
      
      # Setup R
      - name: Setup dependencies
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'


      # Run Scraper R Script
      - name: Scrape Data
        run: Rscript -e 'here::here("scripts/COVID_scrape_current_day.R")'

      # Knits R Markdown
      - name: Knit Report
        run: Rscript -e 'rmarkdown::render("docs/index.Rmd")'
      
      # Authenticate and commit
      - name: Setup git config 
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: commit
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add docs/*
          git commit -m "GH ACTION Headlines $(date)"
          git push origin main
# Complete Job

